title: "Racine n'CO"
description: "Le site des Racines"
baseurl: "" # Laisser vide pour GitHub Pages
url: "https://https://petitmillefa.github.io"
theme: minima # Optionnel, mais vous pouvez personnaliser avec un thème
markdown: kramdown

# Navigation du site
nav:
  - name: "Accueil"
    link: "/"
  - name: "Actualités"
    link: "/news/"
  - name: "Événements"
    link: "/events/"
  - name: "Galerie"
    link: "/gallery/"
  - name: "Contact"
    link: "/contact/"
